---
  .travis.yml:
    hc_secure: "l2v0jHQSkLOEwNbotBmhOfbbxSm7F2vkNU8R7Noytyw9AV7AVOdZNIaH3R/g\\nZe8sBZn29r7ShyF4Z4WmgA2NeckTVnipRaSaSLodCj6qqfUeNY87O2kw7B8j\\n6jDRLCWmecw2siYVTz/qX8fT/AQ30I5xiVFzFu3lMwQshprHY/8="
