---
  .travis.yml:
    hc_secure: "l2v0jHQSkLOEwNbotBmhOfbbxSm7F2vkNU8R7Noytyw9AV7AVOdZNIaH3R/g\\nZe8sBZn29r7ShyF4Z4WmgA2NeckTVnipRaSaSLodCj6qqfUeNY87O2kw7B8j\\n6jDRLCWmecw2siYVTz/qX8fT/AQ30I5xiVFzFu3lMwQshprHY/8="
  spec/acceptance/nodesets/centos-65-x64.yml:
    delete: true
  spec/acceptance/nodesets/centos-70-x64.yml:
    delete: true
  spec/acceptance/nodesets/ubuntu-server-1204-x64.yml:
    delete: true
  spec/acceptance/nodesets/ubuntu-server-1404-x64.yml:
    delete: true

